#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: dishedraprl
    gecos: dishedraprl
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa blah blah


# package_update: true

# Downloads the packages
packages:
  - python3-pip

# Setsthe GOPATH & downloads the demo payload
runcmd:
  - cd /home/dishendraprl
  - git clone https://github.com/Dishendramishra/simtess-bot
  - cd simtess-bot
  - pip3 install -r requirements.txt

# final_message: "The system is finally up, after $UPTIME seconds"